default: &default
  schema_search_path: public

development:
  <<: *default
  host:     <%= ENV['HOST']     ||'127.0.0.1'         %>
  port:     <%= ENV['PORT']     ||3306                %>
  pool:     <%= ENV['POOL']     ||5                   %>
  adapter:  <%= ENV['ADAPTER']  ||'mysql2'            %>
  encoding: <%= ENV['IENCODING']||'utf8'              %>
  username: <%= ENV['USERNAME'] ||'root'              %>
  password: <%= ENV['PASSWORD'] ||''                  %>
  database: <%= ENV['DATABASE'] ||'ineye_website_dev' %>

production:
  <<: *default
  host:     <%= ENV['HOST']     ||''%>
  port:     <%= ENV['PORT']     ||3306%>
  pool:     <%= ENV['POOL']     ||5%>
  adapter:  <%= ENV['ADAPTER']  ||'mysql2'%>
  encoding: <%= ENV['ENCODING'] ||'utf8'%>
  username: <%= ENV['USERNAME'] ||'hesheng'%>
  password: <%= ENV['PASSWORD'] ||''%>
  database: <%= ENV['DATABASE'] ||'ineye_website_dev'%>