default: &default
  schema_search_path: public

development:
  <<: *default
  host:     <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_HOST']    ||'127.0.0.1'     %>
  port:     <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_PORT']    ||3306            %>
  pool:     <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_POOL']    ||5               %>
  adapter:  <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_ADAPTER'] ||'mysql2'        %>
  encoding: <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_ENCODING']||'utf8'          %>
  username: <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_USERNAME']||'root'          %>
  password: <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_PASSWORD']||''              %>
  database: <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_NAME']    ||'ineye_website' %>

test:
  <<: *default
  host:     <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_HOST']    ||'127.0.0.1'     %>
  port:     <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_PORT']    ||3306            %>
  pool:     <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_POOL']    ||5               %>
  adapter:  <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_ADAPTER'] ||'mysql2'        %>
  encoding: <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_ENCODING']||'utf8'          %>
  username: <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_USERNAME']||'root'          %>
  password: <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_PASSWORD']||''              %>
  database: <%= ENV['INEYE_WEBSITE_DEVELOPMENT_DATABASE_NAME']    ||'ineye_website' %>

production:
  <<: *default
  host:     <%= ENV['INEYE_WEBSITE_PRODUCTION_DATABASE_HOST']    ||'127.0.0.1'     %>
  port:     <%= ENV['INEYE_WEBSITE_PRODUCTION_DATABASE_PORT']    ||3306            %>
  pool:     <%= ENV['INEYE_WEBSITE_PRODUCTION_DATABASE_POOL']    ||5               %>
  adapter:  <%= ENV['INEYE_WEBSITE_PRODUCTION_DATABASE_ADAPTER'] ||'mysql2'        %>
  encoding: <%= ENV['INEYE_WEBSITE_PRODUCTION_DATABASE_ENCODING']||'utf8'          %>
  username: <%= ENV['INEYE_WEBSITE_PRODUCTION_DATABASE_USERNAME']||'root'          %>
  password: <%= ENV['INEYE_WEBSITE_PRODUCTION_DATABASE_PASSWORD']||''              %>
  database: <%= ENV['INEYE_WEBSITE_PRODUCTION_DATABASE_NAME']    ||'ineye_website' %>